version : '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: dk_mysql
    command: --init-file /data/application/spotify.sql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root

    volumes:
    - ./spotify.sql:/data/application/spotify.sql
    - ../docker/data-mysql:/var/lib/mysql




  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dk_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80