CREATE DATABASE IF NOT EXISTS spotifyyyy;

USE spotifyyyy;


CREATE TABLE `PLAN` (
	`ID` int NOT NULL AUTO_INCREMENT,
	`NAME` varchar(20) NOT NULL,
	`PRICE` int NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `USER` (
	`ID` int NOT NULL AUTO_INCREMENT,
	`NAME` varchar(20) NOT NULL,
	`LASTNAME` varchar(30) NOT NULL,
	`DATE_OF_BIRTH` DATE NOT NULL,
	`ADDRESS` varchar(100) NOT NULL,
	`CONTRACT` int NOT NULL,
	`EMAIL` varchar(50) NOT NULL,
	`PASSWORD` varchar(100) NOT NULL,
	`USER_TYPE_ID` int NOT NULL,
	`COUNTRY` varchar(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `USER_TYPE` (
	`ID` int NOT NULL AUTO_INCREMENT,
	`TYPE` varchar(20) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `CONTRACT` (
	`ID` int NOT NULL AUTO_INCREMENT,
	`NUMBER` int NOT NULL,
	`PLAN_ID` int NOT NULL,
	`PAY_METHOD` int NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `SONGS` (
	`ID` int NOT NULL AUTO_INCREMENT,
	`TITLE` varchar(255) NOT NULL,
	`ARTIST_ID` int NOT NULL,
	`ALBUM_ID` int NOT NULL,
	`DURATION_MS` int NOT NULL,
	`LIKES` int NOT NULL,
	`PLAYS` int NOT NULL,
	`GENRE_ID` int NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `ALBUM` (
	`ID` int NOT NULL AUTO_INCREMENT,
	`TITLE` varchar(255) NOT NULL,
	`ARTIST` varchar(255) NOT NULL,
	`DATE` year(4) NOT NULL,
	`COVER` mediumblob NOT NULL,
	`GENRE_ID` int NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `GENRE` (
	`ID` int NOT NULL AUTO_INCREMENT,
	`NAME` varchar(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `ARTIST` (
	`ID` int NOT NULL AUTO_INCREMENT,
	`NAME` varchar(255) NOT NULL,
	`LASTNAME` varchar(255) NOT NULL,
	`ALIAS` varchar(255) NOT NULL,
	`PHOTO` mediumblob NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `LIBRARY_USER` (
	`ID_LIBRARY_USER` int NOT NULL AUTO_INCREMENT,
	`USER_ID` int NOT NULL,
	`SONG_ID` int NOT NULL,
	`PLAYLIST_USER_ID` int NOT NULL,
	`PLAYLIST_PUBLIC_ID` int NOT NULL,
	PRIMARY KEY (`ID_LIBRARY_USER`)
);

CREATE TABLE `PLAYLIST_USER` (
	`ID_PLAYLIST_USER` int NOT NULL,
	`SONG_ID` int NOT NULL,
	`COVER` mediumblob NOT NULL,
	PRIMARY KEY (`ID_PLAYLIST_USER`)
);

CREATE TABLE `PLAYLIST_PUBLIC` (
	`ID_PLAYLIST_PUBLIC` int NOT NULL,
	`SONG_ID` int NOT NULL,
	`COVER` mediumblob NOT NULL,
	PRIMARY KEY (`ID_PLAYLIST_PUBLIC`)
);

ALTER TABLE `USER` ADD CONSTRAINT `USER_fk0` FOREIGN KEY (`CONTRACT`) REFERENCES `CONTRACT`(`ID`);

ALTER TABLE `USER` ADD CONSTRAINT `USER_fk1` FOREIGN KEY (`USER_TYPE_ID`) REFERENCES `USER_TYPE`(`ID`);

ALTER TABLE `CONTRACT` ADD CONSTRAINT `CONTRACT_fk0` FOREIGN KEY (`PLAN_ID`) REFERENCES `PLAN`(`ID`);

ALTER TABLE `CONTRACT` ADD CONSTRAINT `CONTRACT_fk1` FOREIGN KEY (`PAY_METHOD`) REFERENCES ``(``);

ALTER TABLE `SONGS` ADD CONSTRAINT `SONGS_fk0` FOREIGN KEY (`ARTIST_ID`) REFERENCES `ARTIST`(`ID`);

ALTER TABLE `SONGS` ADD CONSTRAINT `SONGS_fk1` FOREIGN KEY (`ALBUM_ID`) REFERENCES `ALBUM`(`ID`);

ALTER TABLE `SONGS` ADD CONSTRAINT `SONGS_fk2` FOREIGN KEY (`GENRE_ID`) REFERENCES `GENRE`(`ID`);

ALTER TABLE `ALBUM` ADD CONSTRAINT `ALBUM_fk0` FOREIGN KEY (`GENRE_ID`) REFERENCES `GENRE`(`ID`);

ALTER TABLE `LIBRARY_USER` ADD CONSTRAINT `LIBRARY_USER_fk0` FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`ID`);

ALTER TABLE `LIBRARY_USER` ADD CONSTRAINT `LIBRARY_USER_fk1` FOREIGN KEY (`SONG_ID`) REFERENCES `SONGS`(`ID`);

ALTER TABLE `LIBRARY_USER` ADD CONSTRAINT `LIBRARY_USER_fk2` FOREIGN KEY (`PLAYLIST_USER_ID`) REFERENCES `PLAYLIST_USER`(`ID_PLAYLIST_USER`);

ALTER TABLE `LIBRARY_USER` ADD CONSTRAINT `LIBRARY_USER_fk3` FOREIGN KEY (`PLAYLIST_PUBLIC_ID`) REFERENCES `PLAYLIST_PUBLIC`(`ID_PLAYLIST_PUBLIC`);

