--Vista 1 Sesiones de Usuarios

CREATE VIEW VISTA_SESIONES AS

SELECT NAME, SESSION_LOGOUT, LOGIN_COUNT FROM USER, USER_SESSION WHERE USER.ID = USER_SESSION.USER_ID;

SELECT * FROM VISTA_SESIONES;

--Vista 2 Crear una tabla songs_play que tenga id_song e id_usuario e veces reproducidas

--Vista 3 Usuario login

CREATE VIEW VISTA_USUARIOS AS

SELECT NAME, SESSION_LOGIN FROM USER, USER_SESSION WHERE USER.ID = USER_SESSION.USER_ID;

SELECT * FROM VISTA_SESIONES;